# Generated by Django 3.0.5 on 2021-06-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='c_created_by',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='t_created_by',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
