# Generated by Django 3.0.5 on 2021-06-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_auto_20210622_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='p_created_by',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
