# Generated by Django 3.0.5 on 2021-07-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_payment_p_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_username', models.CharField(max_length=30, null=True)),
                ('to_username', models.CharField(max_length=30, null=True)),
                ('task_name', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmApp.task')),
            ],
        ),
    ]
