# Generated by Django 3.0.5 on 2021-07-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_username', models.CharField(max_length=30, null=True)),
                ('to_username', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('m_time', models.CharField(max_length=30, null=True)),
                ('m_status', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
