# Generated by Django 3.2.4 on 2022-10-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_usernotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='c_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='c_desc',
        ),
        migrations.AlterField(
            model_name='client',
            name='c_university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
